
const CONS_EMAIL = "email"
const CONS_PASSWORD = "password"
const CONS_USERNAME = "username"
const CONS_PHOTO = "photo"

export {CONS_EMAIL, CONS_PASSWORD,CONS_USERNAME, CONS_PHOTO };


const PRIMARY_COLOR = "#18A0FB"
const BUTTON_COLOR = "574C63"
const BKG_COLOR = "200E32"
export {PRIMARY_COLOR, BUTTON_COLOR, BKG_COLOR}